# The ServiceAccount used by the Kroxylicious Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kroxylicious-operator
  namespace: kroxylicious-operator
  labels:
    app.kubernetes.io/name: kroxylicious
    app.kubernetes.io/component: operator
