apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: proxy
  namespace: my-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kroxylicious
      app.kubernetes.io/component: proxy
  podMetricsEndpoints:
    - path: /metrics
      port: management
